theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
color-modes = true
cursorline = true
true-color = true
idle-timeout = 100
completion-timeout = 100
preview-completion-insert = true
completion-trigger-len = 1
text-width = 100
rulers = [80, 100]
auto-format = true
# clipboard-provider = "pasteboard"

[editor.auto-save]
focus-lost = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = false

[editor.whitespace]
render = "all"
characters.space = "·"
characters.nbsp = "⍽"
characters.tab = "→"
characters.newline = "⏎"
characters.tabpad = " "
characters.spacepad = " "
characters.trailing = "·"

[editor.search]
smart-case = true
wrap-around = true

[editor.file-picker]
hidden = false
git-ignore = true

[keys.normal]
"C-s" = ":write"
"C-q" = ":quit"

[keys.insert]
"C-s" = ":write"
"C-q" = ":quit"
j = { k = "normal_mode" }

[keys.normal.space]
"w" = ":write"
"q" = ":quit"
"Q" = ":quit!"
"f" = ":format"
"x" = ":x"
